filebeat:
  spool_size: 2048
  idle_timeout: 1s
  registry_file: /filebeat/registry

  prospectors:
  - type: log
    paths:
      - /logs/app/stash.*.log
    input_type: log
    json.keys_under_root: true
    json.add_error_key: true
    ignore_older: 24h
    scan_frequency: 10s
    close_inactive: 5m
    close_removed: true
    clean_removed: true
    clean_inactive: 25h
#    input_type: log
#    fields:
#      environment: devcondockerdemo
#      index_environment: devcondockerdemo
#    fields_under_root: true
#    document_type: stash-logs

name: devcon-docker-demo-filebeat-shipper

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  index: "filebeat-%{+yyyy.MM.dd}"

